org: sebastian97
app: python-test
service: python-test

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: python3.8
  profile: default
  lambdaHashingVersion: 20201221

functions:
  llamada:
    handler: handler.llamada
    events:
      - http:
          path: /Llamada
          method: POST 
  NuevoDolar:
    handler: handler.NuevoDolar
    events:
      - schedule: rate(5 minutes)
  TestingData:
    handler: handler.TestingData
    events:
      - http:
          path: /ListaTabla
          method: GET
plugins:
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline
  
resources:
  Resources:
    DolarDia:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DolarDia
        AttributeDefinitions:
          - AttributeName: fecha
            AttributeType: S
        KeySchema:
          - AttributeName: fecha
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
custom:
  dynamodb:
    stages:
      - dev